import type { CSSProperties, ReactNode } from "react";

export type PillTone = "muted" | "active" | "done" | "warn" | "error" | "info";

/**
 * Canonical status pill. Mono uppercase label with a leading dot in the tone
 * colour. The dot is generated by CSS — children are the label only.
 */
export function Pill({
  tone = "muted",
  noDot,
  solid,
  className,
  style,
  children,
}: {
  tone?: PillTone;
  noDot?: boolean;
  solid?: boolean;
  className?: string;
  style?: CSSProperties;
  children: ReactNode;
}) {
  const cls = ["pill", noDot && "no-dot", solid && "solid", className].filter(Boolean).join(" ");
  return (
    <span className={cls} data-tone={tone} style={style}>
      {children}
    </span>
  );
}
