// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelDownloadData, CancelDownloadErrors, CancelDownloadResponses, CreateDownloadData, CreateDownloadErrors, CreateDownloadResponses, GetConfigData, GetConfigResponses, GetDownloadData, GetDownloadErrors, GetDownloadProgressData, GetDownloadProgressErrors, GetDownloadProgressResponses, GetDownloadResponses, GetHealthData, GetHealthResponses, ListDownloadsData, ListDownloadsResponses, PutConfigData, PutConfigErrors, PutConfigResponses, RequeueDownloadData, RequeueDownloadErrors, RequeueDownloadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List Downloads
 */
export const listDownloads = <ThrowOnError extends boolean = false>(options?: Options<ListDownloadsData, ThrowOnError>) => (options?.client ?? client).get<ListDownloadsResponses, unknown, ThrowOnError>({ url: '/api/downloads', ...options });

/**
 * Create Download
 */
export const createDownload = <ThrowOnError extends boolean = false>(options: Options<CreateDownloadData, ThrowOnError>) => (options.client ?? client).post<CreateDownloadResponses, CreateDownloadErrors, ThrowOnError>({
    url: '/api/downloads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Download
 */
export const getDownload = <ThrowOnError extends boolean = false>(options: Options<GetDownloadData, ThrowOnError>) => (options.client ?? client).get<GetDownloadResponses, GetDownloadErrors, ThrowOnError>({ url: '/api/downloads/{download_id}', ...options });

/**
 * Cancel Download
 */
export const cancelDownload = <ThrowOnError extends boolean = false>(options: Options<CancelDownloadData, ThrowOnError>) => (options.client ?? client).post<CancelDownloadResponses, CancelDownloadErrors, ThrowOnError>({ url: '/api/downloads/{download_id}/cancel', ...options });

/**
 * Requeue Download
 */
export const requeueDownload = <ThrowOnError extends boolean = false>(options: Options<RequeueDownloadData, ThrowOnError>) => (options.client ?? client).post<RequeueDownloadResponses, RequeueDownloadErrors, ThrowOnError>({ url: '/api/downloads/{download_id}/requeue', ...options });

/**
 * Get Progress
 */
export const getDownloadProgress = <ThrowOnError extends boolean = false>(options: Options<GetDownloadProgressData, ThrowOnError>) => (options.client ?? client).get<GetDownloadProgressResponses, GetDownloadProgressErrors, ThrowOnError>({ url: '/api/downloads/{download_id}/progress', ...options });

/**
 * Get Config
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => (options?.client ?? client).get<GetConfigResponses, unknown, ThrowOnError>({ url: '/api/config', ...options });

/**
 * Put Config
 */
export const putConfig = <ThrowOnError extends boolean = false>(options: Options<PutConfigData, ThrowOnError>) => (options.client ?? client).put<PutConfigResponses, PutConfigErrors, ThrowOnError>({
    url: '/api/config',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
