// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelDownloadData, CancelDownloadErrors, CancelDownloadResponses, CancelMaintenanceJobData, CancelMaintenanceJobErrors, CancelMaintenanceJobResponses, CheckForUpdatesData, CheckForUpdatesErrors, CheckForUpdatesResponses, CreateDownloadData, CreateDownloadErrors, CreateDownloadResponses, CreateOutputDirData, CreateOutputDirErrors, CreateOutputDirResponses, DeleteTargetData, DeleteTargetErrors, DeleteTargetResponses, ExportLibraryData, ExportLibraryResponses, GetConfigData, GetConfigResponses, GetDownloadData, GetDownloadErrors, GetDownloadProgressData, GetDownloadProgressErrors, GetDownloadProgressResponses, GetDownloadResponses, GetHealthData, GetHealthResponses, GetMaintenanceJobProgressData, GetMaintenanceJobProgressErrors, GetMaintenanceJobProgressResponses, GetTargetData, GetTargetErrors, GetTargetResponses, GetUpdatePreviewRefData, GetUpdatePreviewRefResponses, ImportLibraryData, ImportLibraryResponses, ListDownloadsData, ListDownloadsResponses, ListMaintenanceJobsData, ListMaintenanceJobsResponses, ListOutputDirsData, ListOutputDirsResponses, ListTargetsData, ListTargetsResponses, PollTargetData, PollTargetErrors, PollTargetResponses, PollWatchedTargetsData, PollWatchedTargetsResponses, PutConfigData, PutConfigErrors, PutConfigResponses, RequeueDownloadData, RequeueDownloadErrors, RequeueDownloadResponses, ScheduleMaintenanceJobData, ScheduleMaintenanceJobErrors, ScheduleMaintenanceJobResponses, SetUpdatePreviewRefData, SetUpdatePreviewRefErrors, SetUpdatePreviewRefResponses, TailLogsApiLogsTailGetData, TailLogsApiLogsTailGetErrors, TailLogsApiLogsTailGetResponses, UpdateTargetData, UpdateTargetErrors, UpdateTargetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List Downloads
 */
export const listDownloads = <ThrowOnError extends boolean = false>(options?: Options<ListDownloadsData, ThrowOnError>) => (options?.client ?? client).get<ListDownloadsResponses, unknown, ThrowOnError>({ url: '/api/downloads', ...options });

/**
 * Create Download
 */
export const createDownload = <ThrowOnError extends boolean = false>(options: Options<CreateDownloadData, ThrowOnError>) => (options.client ?? client).post<CreateDownloadResponses, CreateDownloadErrors, ThrowOnError>({
    url: '/api/downloads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Download
 */
export const getDownload = <ThrowOnError extends boolean = false>(options: Options<GetDownloadData, ThrowOnError>) => (options.client ?? client).get<GetDownloadResponses, GetDownloadErrors, ThrowOnError>({ url: '/api/downloads/{download_id}', ...options });

/**
 * Cancel Download
 */
export const cancelDownload = <ThrowOnError extends boolean = false>(options: Options<CancelDownloadData, ThrowOnError>) => (options.client ?? client).post<CancelDownloadResponses, CancelDownloadErrors, ThrowOnError>({ url: '/api/downloads/{download_id}/cancel', ...options });

/**
 * Requeue Download
 */
export const requeueDownload = <ThrowOnError extends boolean = false>(options: Options<RequeueDownloadData, ThrowOnError>) => (options.client ?? client).post<RequeueDownloadResponses, RequeueDownloadErrors, ThrowOnError>({ url: '/api/downloads/{download_id}/requeue', ...options });

/**
 * Get Progress
 */
export const getDownloadProgress = <ThrowOnError extends boolean = false>(options: Options<GetDownloadProgressData, ThrowOnError>) => (options.client ?? client).get<GetDownloadProgressResponses, GetDownloadProgressErrors, ThrowOnError>({ url: '/api/downloads/{download_id}/progress', ...options });

/**
 * List Targets
 */
export const listTargets = <ThrowOnError extends boolean = false>(options?: Options<ListTargetsData, ThrowOnError>) => (options?.client ?? client).get<ListTargetsResponses, unknown, ThrowOnError>({ url: '/api/targets', ...options });

/**
 * Delete Target
 */
export const deleteTarget = <ThrowOnError extends boolean = false>(options: Options<DeleteTargetData, ThrowOnError>) => (options.client ?? client).delete<DeleteTargetResponses, DeleteTargetErrors, ThrowOnError>({ url: '/api/targets/{target_id}', ...options });

/**
 * Get Target
 */
export const getTarget = <ThrowOnError extends boolean = false>(options: Options<GetTargetData, ThrowOnError>) => (options.client ?? client).get<GetTargetResponses, GetTargetErrors, ThrowOnError>({ url: '/api/targets/{target_id}', ...options });

/**
 * Update Target
 */
export const updateTarget = <ThrowOnError extends boolean = false>(options: Options<UpdateTargetData, ThrowOnError>) => (options.client ?? client).patch<UpdateTargetResponses, UpdateTargetErrors, ThrowOnError>({
    url: '/api/targets/{target_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Poll Watched Targets
 *
 * Queue a download for every watched series that may still get chapters.
 *
 * Mirrors a per-target poll fanned out over the watched library, minus the
 * 409: targets with an in-flight download are skipped (and counted) so one
 * busy series never fails the batch.
 */
export const pollWatchedTargets = <ThrowOnError extends boolean = false>(options?: Options<PollWatchedTargetsData, ThrowOnError>) => (options?.client ?? client).post<PollWatchedTargetsResponses, unknown, ThrowOnError>({ url: '/api/targets/poll-watched', ...options });

/**
 * Poll Target
 */
export const pollTarget = <ThrowOnError extends boolean = false>(options: Options<PollTargetData, ThrowOnError>) => (options.client ?? client).post<PollTargetResponses, PollTargetErrors, ThrowOnError>({ url: '/api/targets/{target_id}/poll', ...options });

/**
 * List Output Dirs
 */
export const listOutputDirs = <ThrowOnError extends boolean = false>(options?: Options<ListOutputDirsData, ThrowOnError>) => (options?.client ?? client).get<ListOutputDirsResponses, unknown, ThrowOnError>({ url: '/api/output-dirs', ...options });

/**
 * Create Output Dir
 */
export const createOutputDir = <ThrowOnError extends boolean = false>(options: Options<CreateOutputDirData, ThrowOnError>) => (options.client ?? client).post<CreateOutputDirResponses, CreateOutputDirErrors, ThrowOnError>({
    url: '/api/output-dirs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Config
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => (options?.client ?? client).get<GetConfigResponses, unknown, ThrowOnError>({ url: '/api/config', ...options });

/**
 * Put Config
 */
export const putConfig = <ThrowOnError extends boolean = false>(options: Options<PutConfigData, ThrowOnError>) => (options.client ?? client).put<PutConfigResponses, PutConfigErrors, ThrowOnError>({
    url: '/api/config',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Export Library
 */
export const exportLibrary = <ThrowOnError extends boolean = false>(options?: Options<ExportLibraryData, ThrowOnError>) => (options?.client ?? client).get<ExportLibraryResponses, unknown, ThrowOnError>({ url: '/api/library/export', ...options });

/**
 * Import Library
 */
export const importLibrary = <ThrowOnError extends boolean = false>(options?: Options<ImportLibraryData, ThrowOnError>) => (options?.client ?? client).post<ImportLibraryResponses, unknown, ThrowOnError>({ url: '/api/library/import', ...options });

/**
 * List Maintenance Jobs
 */
export const listMaintenanceJobs = <ThrowOnError extends boolean = false>(options?: Options<ListMaintenanceJobsData, ThrowOnError>) => (options?.client ?? client).get<ListMaintenanceJobsResponses, unknown, ThrowOnError>({ url: '/api/maintenance/jobs', ...options });

/**
 * Schedule Maintenance Job
 */
export const scheduleMaintenanceJob = <ThrowOnError extends boolean = false>(options: Options<ScheduleMaintenanceJobData, ThrowOnError>) => (options.client ?? client).post<ScheduleMaintenanceJobResponses, ScheduleMaintenanceJobErrors, ThrowOnError>({
    url: '/api/maintenance/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel Maintenance Job
 */
export const cancelMaintenanceJob = <ThrowOnError extends boolean = false>(options: Options<CancelMaintenanceJobData, ThrowOnError>) => (options.client ?? client).post<CancelMaintenanceJobResponses, CancelMaintenanceJobErrors, ThrowOnError>({ url: '/api/maintenance/jobs/{job_id}/cancel', ...options });

/**
 * Check For Updates Endpoint
 *
 * Compare the installed checkout to the tracked ref on GitHub.
 *
 * The tracked ref defaults to whatever's in `.git/HEAD` (`main` in
 * production) but can be overridden via `PUT /maintenance/update-ref`
 * to preview an unreleased branch / tag / SHA. `force=true` bypasses
 * the 60 s in-process cache for an explicit refresh button; default
 * polling reuses the cached result so the UI can refetch aggressively
 * without burning GitHub's anon rate limit.
 */
export const checkForUpdates = <ThrowOnError extends boolean = false>(options?: Options<CheckForUpdatesData, ThrowOnError>) => (options?.client ?? client).get<CheckForUpdatesResponses, CheckForUpdatesErrors, ThrowOnError>({ url: '/api/maintenance/update-check', ...options });

/**
 * Get Update Preview Ref
 *
 * Return the currently-configured preview ref, or null for the default.
 *
 * Stored in app_config under `update_preview_ref` so it persists across
 * restarts. When null, the update checker uses the branch from
 * `.git/HEAD` (production: `main`).
 */
export const getUpdatePreviewRef = <ThrowOnError extends boolean = false>(options?: Options<GetUpdatePreviewRefData, ThrowOnError>) => (options?.client ?? client).get<GetUpdatePreviewRefResponses, unknown, ThrowOnError>({ url: '/api/maintenance/update-ref', ...options });

/**
 * Set Update Preview Ref
 *
 * Persist a preview ref, or clear it when null/empty.
 *
 * No upstream validation here: a wrong ref will surface as
 * `branch_not_on_remote` from the next `/update-check`, and the user
 * can fix it without the round-trip + rate-limit cost of an extra
 * GitHub call per save.
 */
export const setUpdatePreviewRef = <ThrowOnError extends boolean = false>(options: Options<SetUpdatePreviewRefData, ThrowOnError>) => (options.client ?? client).put<SetUpdatePreviewRefResponses, SetUpdatePreviewRefErrors, ThrowOnError>({
    url: '/api/maintenance/update-ref',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Maintenance Job Progress
 */
export const getMaintenanceJobProgress = <ThrowOnError extends boolean = false>(options: Options<GetMaintenanceJobProgressData, ThrowOnError>) => (options.client ?? client).get<GetMaintenanceJobProgressResponses, GetMaintenanceJobProgressErrors, ThrowOnError>({ url: '/api/maintenance/jobs/{job_id}/progress', ...options });

/**
 * Tail Logs
 *
 * SSE stream of the running service's journal entries.
 *
 * The response is `text/event-stream`. Two event types are emitted:
 * `ready` once at the start carrying `{unit, lines}`, then `log` per entry
 * carrying `{ts_ms, priority, level, message, unit, ident, pid}`. A single
 * `error` event is sent if the host doesn't have journalctl available.
 */
export const tailLogsApiLogsTailGet = <ThrowOnError extends boolean = false>(options?: Options<TailLogsApiLogsTailGetData, ThrowOnError>) => (options?.client ?? client).get<TailLogsApiLogsTailGetResponses, TailLogsApiLogsTailGetErrors, ThrowOnError>({ url: '/api/logs/tail', ...options });
