// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8765' | (string & {});
};

/**
 * AppConfigIn
 */
export type AppConfigIn = {
    /**
     * Postprocess Root
     */
    postprocess_root: string | null;
    /**
     * Postprocess Default Output Dir
     */
    postprocess_default_output_dir: string | null;
    /**
     * Delete Raw After Pack
     */
    delete_raw_after_pack: boolean;
};

/**
 * AppConfigOut
 */
export type AppConfigOut = {
    /**
     * Postprocess Root
     */
    postprocess_root: string | null;
    /**
     * Postprocess Default Output Dir
     */
    postprocess_default_output_dir: string | null;
    /**
     * Postprocess Known Output Dirs
     */
    postprocess_known_output_dirs: Array<string>;
    /**
     * Delete Raw After Pack
     */
    delete_raw_after_pack: boolean;
};

/**
 * ChapterProgress
 */
export type ChapterProgress = {
    /**
     * Name
     */
    name: string;
    /**
     * Files Total
     */
    files_total: number;
    /**
     * Files Present
     */
    files_present: number;
};

/**
 * DownloadCreate
 */
export type DownloadCreate = {
    /**
     * Url
     */
    url: string;
    /**
     * Output Dir
     */
    output_dir?: string | null;
};

/**
 * DownloadOut
 */
export type DownloadOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Url
     */
    url: string;
    /**
     * Extractor
     */
    extractor: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Exit Code
     */
    exit_code: number | null;
    /**
     * Files Downloaded
     */
    files_downloaded: number;
    /**
     * Files Expected
     */
    files_expected: number | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Postprocess Status
     */
    postprocess_status: string | null;
    /**
     * Postprocess Chapters Packed
     */
    postprocess_chapters_packed: number | null;
    /**
     * Postprocess Error
     */
    postprocess_error: string | null;
    /**
     * Output Dir
     */
    output_dir: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProgressOut
 */
export type ProgressOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Files Expected
     */
    files_expected: number | null;
    /**
     * Files Present
     */
    files_present: number;
    /**
     * Chapters
     */
    chapters: Array<ChapterProgress>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Response Gethealth
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListDownloadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/downloads';
};

export type ListDownloadsResponses = {
    /**
     * Response Listdownloads
     *
     * Successful Response
     */
    200: Array<DownloadOut>;
};

export type ListDownloadsResponse = ListDownloadsResponses[keyof ListDownloadsResponses];

export type CreateDownloadData = {
    body: DownloadCreate;
    path?: never;
    query?: never;
    url: '/api/downloads';
};

export type CreateDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDownloadError = CreateDownloadErrors[keyof CreateDownloadErrors];

export type CreateDownloadResponses = {
    /**
     * Successful Response
     */
    200: DownloadOut;
};

export type CreateDownloadResponse = CreateDownloadResponses[keyof CreateDownloadResponses];

export type GetDownloadData = {
    body?: never;
    path: {
        /**
         * Download Id
         */
        download_id: number;
    };
    query?: never;
    url: '/api/downloads/{download_id}';
};

export type GetDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDownloadError = GetDownloadErrors[keyof GetDownloadErrors];

export type GetDownloadResponses = {
    /**
     * Successful Response
     */
    200: DownloadOut;
};

export type GetDownloadResponse = GetDownloadResponses[keyof GetDownloadResponses];

export type CancelDownloadData = {
    body?: never;
    path: {
        /**
         * Download Id
         */
        download_id: number;
    };
    query?: never;
    url: '/api/downloads/{download_id}/cancel';
};

export type CancelDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelDownloadError = CancelDownloadErrors[keyof CancelDownloadErrors];

export type CancelDownloadResponses = {
    /**
     * Successful Response
     */
    200: DownloadOut;
};

export type CancelDownloadResponse = CancelDownloadResponses[keyof CancelDownloadResponses];

export type RequeueDownloadData = {
    body?: never;
    path: {
        /**
         * Download Id
         */
        download_id: number;
    };
    query?: never;
    url: '/api/downloads/{download_id}/requeue';
};

export type RequeueDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequeueDownloadError = RequeueDownloadErrors[keyof RequeueDownloadErrors];

export type RequeueDownloadResponses = {
    /**
     * Successful Response
     */
    200: DownloadOut;
};

export type RequeueDownloadResponse = RequeueDownloadResponses[keyof RequeueDownloadResponses];

export type GetDownloadProgressData = {
    body?: never;
    path: {
        /**
         * Download Id
         */
        download_id: number;
    };
    query?: never;
    url: '/api/downloads/{download_id}/progress';
};

export type GetDownloadProgressErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDownloadProgressError = GetDownloadProgressErrors[keyof GetDownloadProgressErrors];

export type GetDownloadProgressResponses = {
    /**
     * Successful Response
     */
    200: ProgressOut;
};

export type GetDownloadProgressResponse = GetDownloadProgressResponses[keyof GetDownloadProgressResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigResponses = {
    /**
     * Successful Response
     */
    200: AppConfigOut;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type PutConfigData = {
    body: AppConfigIn;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type PutConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutConfigError = PutConfigErrors[keyof PutConfigErrors];

export type PutConfigResponses = {
    /**
     * Successful Response
     */
    200: AppConfigOut;
};

export type PutConfigResponse = PutConfigResponses[keyof PutConfigResponses];
