// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createDownload, getDownload, getDownloadProgress, getHealth, listDownloads, type Options } from '../sdk.gen';
import type { CreateDownloadData, CreateDownloadError, CreateDownloadResponse, GetDownloadData, GetDownloadError, GetDownloadProgressData, GetDownloadProgressError, GetDownloadProgressResponse, GetDownloadResponse, GetHealthData, GetHealthResponse, ListDownloadsData, ListDownloadsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Health
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const listDownloadsQueryKey = (options?: Options<ListDownloadsData>) => createQueryKey('listDownloads', options);

/**
 * List Downloads
 */
export const listDownloadsOptions = (options?: Options<ListDownloadsData>) => queryOptions<ListDownloadsResponse, DefaultError, ListDownloadsResponse, ReturnType<typeof listDownloadsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDownloads({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDownloadsQueryKey(options)
});

/**
 * Create Download
 */
export const createDownloadMutation = (options?: Partial<Options<CreateDownloadData>>): UseMutationOptions<CreateDownloadResponse, CreateDownloadError, Options<CreateDownloadData>> => {
    const mutationOptions: UseMutationOptions<CreateDownloadResponse, CreateDownloadError, Options<CreateDownloadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createDownload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDownloadQueryKey = (options: Options<GetDownloadData>) => createQueryKey('getDownload', options);

/**
 * Get Download
 */
export const getDownloadOptions = (options: Options<GetDownloadData>) => queryOptions<GetDownloadResponse, GetDownloadError, GetDownloadResponse, ReturnType<typeof getDownloadQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDownload({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDownloadQueryKey(options)
});

export const getDownloadProgressQueryKey = (options: Options<GetDownloadProgressData>) => createQueryKey('getDownloadProgress', options);

/**
 * Get Progress
 */
export const getDownloadProgressOptions = (options: Options<GetDownloadProgressData>) => queryOptions<GetDownloadProgressResponse, GetDownloadProgressError, GetDownloadProgressResponse, ReturnType<typeof getDownloadProgressQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDownloadProgress({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDownloadProgressQueryKey(options)
});
